encoder_model_name: "DenseEncoder"
encoder_model_params: {in_dim: 768, hidden_dims: [256, 128], out_dim: 64} # encoder_model_params: {in_dim: 384, hidden_dims: [512, 256], out_dim: 64}
num_enc_epochs: 20
encoder_learning_rate: 1e-3
